[package]
name = "clonedir_lib"
version = "0.1.2-alpha.0"
authors = ["Jeff Dickey <@jdxcode>"]
license = "MIT"
description = "clone a directory with copy-on-write"
repository = "https://github.com/jdxcode/clonedir_lib"

[dependencies]
reflink = "0.1.2"
env_logger = "0.5.13"
log = "0.4.5"
